### ISSUE TITLE
Websocket 4004 Error

### ISSUE THREAD

**Issue by blubaustin** [romainisnel/hertz#17]
Anytime I try to launch the bot I get a Websocket 4004 error. Ensured my token is correct and it is so I don't know if there is a stack trace ability to see what's going on or?

**Comment by romainisnel** [comment]
Hello @blubaustin do you have more details on the problem ?

**Comment by blubaustin** [comment]
![image](https://user-images.githubusercontent.com/31782440/48377229-7c4b8700-e68a-11e8-94ae-5d229b486da0.png)

**Comment by blubaustin** [comment]
![image](https://user-images.githubusercontent.com/31782440/48377309-b452ca00-e68a-11e8-9885-abafdb1991ef.png)

**Comment by romainisnel** [comment]
The function loading the JSON configuration was returning an error, hence, the bot was trying to connect to discord with an empty token.

This issue has been fixed in 678c0df17e57ece56863b70e27f4ee35e4a86923.

Let me know if the issue is fixed for you @blubaustin.

**Comment by blubaustin** [comment]
That fixed that error now I have a different error I'll open a new bug report.
